version: '3.7'
services:
  frontend:
    build:
      context: ./chatbot-app
      dockerfile: frontend.dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - backend
    env_file:
      - .env
  backend:
    build: 
      context: ./
      dockerfile: backend.dockerfile
    command: /bin/sh -c "chmod +x ./wait-for-it.sh && ./wait-for-it.sh db:5432 -- npm run server"
    ports:
      - '3000:3000'
    depends_on:
      - db
      # - redis
    env_file:
      - .env
  db:
    image: postgres:12
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  # redis:
  #   image: redis:6.2
  #   restart: always
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis_data:/data

volumes:
  postgres_data:
  redis_data: