name: CI/CD Pipeline

on:
  # Trigger on pushes to the main and dev branch
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./new-chatbot-app
        file: ./new-chatbot-app/backend.dockerfile
        push: true
        tags: tranhvloc/chatbot-app-backend:latest

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./new-chatbot-app/client
        file: ./new-chatbot-app/client/frontend.dockerfile
        push: true
        tags: tranhvloc/chatbot-app-frontend:latest
